name: Update DevCard

# GitHub Actions documentation: https://docs.github.com/en/actions
# GitHub Marketplace Actions: https://github.com/marketplace?type=actions

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '21 */6 * * *' # https://crontab.guru

jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run script
        run: npm start
        env:
          DEVCARD_ID: ${{ vars.DEVCARD_ID }}
      - name: Commit files
        run: |
          git config --global user.email "paul.potaczala@gmail.com"
          git config --global user.name "Paul Potaczała"
          git commit -am "chore(devcard): [NO-REF] Update devcard ⚡" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}