name: Auto update DevCard

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '@daily'

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.2.0
        with:
          devcard_id: ${{ vars.DEVCARD_ID }}