name: DevCard Update Action

# GitHub Actions documentation: https://docs.github.com/en/actions
# GitHub Marketplace Actions: https://github.com/marketplace?type=actions

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '21 */6 * * *' # https://crontab.guru

jobs:
  update-devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.3.0
        with:
          DEVCARD_ID: ${{ vars.DEVCARD_ID }}
          COMMIT_MESSAGE: 'chore(devcard): [NO-REF] Update devcard ⚡'
          COMMITTER_EMAIL: ${{ vars.COMMIT_EMAIL }}
          COMMITTER_NAME: ${{ vars.COMMIT_USERNAME }}