name: DevCard Update Action

# GitHub Actions documentation: https://docs.github.com/en/actions
# GitHub Marketplace Actions: https://github.com/marketplace?type=actions

on:
  schedule:
    - cron: '31 */6 * * *' # https://crontab.guru
  workflow_dispatch:

jobs:
  update-devcard:
    name: Update devcard file
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: dailydotdev/action-devcard@3.2.1
        with:
          COMMIT_MESSAGE: 'chore(devcard): [NO-REF] Update devcard ⚡'
          COMMITTER_EMAIL: ${{ vars.COMMIT_EMAIL }}
          COMMITTER_NAME: ${{ vars.COMMIT_USERNAME }}
          USER_ID: ${{ vars.USER_ID }}