name: Update DevCard

# GitHub Actions documentation: https://docs.github.com/en/actions
# GitHub Marketplace Actions: https://github.com/marketplace?type=actions

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "21 */6 * * *" # https://crontab.guru

jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.2.0
        with:
          devcard_id: ${{ vars.DEVCARD_ID }}
          commit_message: "chore(devcard): [NO-REF] Update ${filename} ⚡️"