name: Duolingo README Stats Action

on:
  schedule:
    - cron: "21 */6 * * *" # https://crontab.guru
  workflow_dispatch:

jobs:
  update-readme:
    name: Update readme with your duolingo stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: centrumek/duolingo-readme-stats@main
        with:
          DUOLINGO_USER_ID: ${{ vars.DUOLINGO_USER_ID }}
          COMMIT_EMAIL: ${{ vars.COMMIT_EMAIL }}
          COMMIT_USERNAME: ${{ vars.COMMIT_USERNAME }}